services:
  vue-app:
    build: 
      context: .
      target: development-stage
    ports:
      - '6969:5173'
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
